### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by ManaliDubal** [mazurio/bodyweight-fitness-android#13]
Hello Mazurio,
Thank you for this great app. 
I have one query though, I have been trying to open this app in Android Studio. But there are many errors. I am sure these are the problems of my gradle files. 
Can I open this code in Android Studio? or I require Eclipse for it?

Thank You,
Manali

**Comment by mazurio** [comment]
Hi Manali,

I use Android Studio, what errors do you have?

**Comment by ManaliDubal** [comment]
Hello Mazurio,
Got them solved. Thank you very much for wonderful app !

Best,
Manali
