### ISSUE TITLE
Force Close after minimizing/closing the app

### ISSUE THREAD

**Issue by Zoxjib** [mazurio/bodyweight-fitness-android#28]
When you push the "+" button in the bottom right and then use the phone's capacitive button to go 'back', instead of closing the menu that "+" opened, the app is closed/minimized.

Once you're back into the app, if you try to go right (to the next exercise), the app force closes.

**Comment by mazurio** [comment]
HI @BullHorn7,

What device/version do you have? I cannot reproduce the "force closes" issue at all with the exact movement.

Thanks,
Damian

**Comment by Zoxjib** [comment]
Nexus 5 (2013) with latest 6.0.1 build (April 2nd 2016)

**Comment by mazurio** [comment]
Thanks @BullHorn7 I will look into it in the evening but I cannot reproduce it on the emulator with the same steps - I was able to make it "slow down" when coming back to it but clicking at it twice works. 

I also cannot see any crashes on Fabric.

**Comment by Zoxjib** [comment]
I just sent a crash report via the FC but I'm not sure if you or Google get it...

**Comment by mazurio** [comment]
Hi @BullHorn7 can you check if the same bug exists in 1.1.9? I have looked into the crash and I think it was fixed properly in 1.1.9 which came out just 1h after 1.1.8.

**Comment by Zoxjib** [comment]
Cannot reproduce with 1.1.9, thanks.

**Comment by mazurio** [comment]
Awesome, seems to be fixed. Thanks for your help!
