### ISSUE TITLE
Exercise name doesn't change 

### ISSUE THREAD

**Issue by scowalt** [mazurio/bodyweight-fitness-android#31]
_Repro steps_
1. Open app 
2. Open app settings 
3. Go back to main screen 
4. Switch exercises 

_Expected_
Exercise name at the top of the screen will change with exercise 

_Actual_
Exercise name doesn't change from the previous exercise. 

100% repro 

Thanks for making the app!

**Comment by mazurio** [comment]
Thanks for opening the issue! Will fix with the next release (100% repro).

**Comment by mazurio** [comment]
Fixed in 1.2.2

**Comment by mazurio** [comment]
Thanks again - I have also fixed the issue where action buttons were being hidden when switching activities. 👍

**Comment by scowalt** [comment]
Cheers! Thanks for all of your work! Will continue to report issues if I find them 😃
