### ISSUE TITLE
Removing empty exercises when changing progressions

### ISSUE THREAD

**Issue by dmouck** [mazurio/bodyweight-fitness-android#40]
When moving up to a new progression, the Today's Workout Log shows missed exercises of the previous progressions.

For example, in Skill work if I change the progression from Level 1 - Wall Plank to Level 2 - Stomach-to-Wall Handstand and log some time or reps, the Today's Progress shows the Wall Plank as a missed exercise. I do not see a way to remove an entry that has a log of 0.

**Comment by mazurio** [comment]
Thanks - will look into it this weekend!

**Comment by mazurio** [comment]
Hi @dmouck - thanks for letting me know. This is now fixed in https://github.com/mazurio/bodyweight-fitness-android/pull/43/commits/3d295e9799d108ee27edea5c5029c15d24c0f5c0 and will be out in the next update with the new menu. Such a bad mistake too!
