### ISSUE TITLE
gradlew file not in repository

### ISSUE THREAD

**Issue by ftc** [mazurio/bodyweight-fitness-android#5]
This is a pretty minor complaint but would you mind including the gradlew file in the repository?  Also I notice that gradlew is part of your .gitignore.

(gradle documentation on the wrapper: https://docs.gradle.org/current/userguide/gradle_wrapper.html )

**Comment by mazurio** [comment]
Sorry didn't realise there was new issue, I blame GitHub notifications!
I don't use the wrapper at all so I thought it just clutters the directory but might add it with this update.

**Comment by ftc** [comment]
Thanks.  It makes it nice for building on the command line since it automatically handles versions of gradle.
