### ISSUE TITLE
Broken navigation on settings tab

### ISSUE THREAD

**Issue by krokofant** [mazurio/bodyweight-fitness-android#50]
The view appears empty after pressing the back button in the settings tab

![Settings screen with back button](https://cloud.githubusercontent.com/assets/5908498/21536721/9c714b9c-cd86-11e6-8aad-957d9cc45efa.gif)

**Comment by theck13** [comment]
That should be fixed with https://github.com/mazurio/bodyweight-fitness-android/commit/f4f1324405523bf571850425059a0fd5e1f42c0d.  Can you still reproduce that on `master`?

**Comment by krokofant** [comment]
Works great on master!

Without creating another issue I'd like to ask, is there any way to import data? I've backed up the app with Titanium Backup but it doesn't seem so flexible, especially when switching between builds 😄
