### ISSUE TITLE
Treat side planks as separate exercises for each side

### ISSUE THREAD

**Issue by annawoodard** [mazurio/bodyweight-fitness-android#55]
Consider treating side planks as separate exercises for each side. My left arm is significantly weaker than my right currently, so I'd like to be able to track progress on each side independently as the left side catches up.

I tried the RR for the first time today, so please mark resolved if I'm missing something fundamental here. Huge props to @mazurio and collaborators for implementing this app-- it's really fantastic, I'm not sure I would have had tried the RR without it!

**Comment by mazurio** [comment]
Hi @annawoodard - the idea of one side plank exercise was that first set is left side and 2nd set is the right side (or opposite). The 2nd exercise would need a different video or one that was mirrored to show different side.

**Comment by annawoodard** [comment]
Thanks @mazurio! Please disregard the reference above, I put the wrong issue number 😞
