### ISSUE TITLE
Leg swings gif incomplete

### ISSUE THREAD

**Issue by Benthem** [mazurio/bodyweight-fitness-android#8]
Gif only shows front leg swings before looping.

**Comment by mazurio** [comment]
The gif was reduced in size, this is why the leg swings are so fast as well. Going to improve it and hopefully introduce .mp4 soon. Thanks!

**Comment by Benthem** [comment]
Perhaps cutting frames and slowing them in a sort of stop-motion fashion is a lightweight solution.

**Comment by mazurio** [comment]
Added ability to see YouTube video in 1.0.2
